# -*- coding: utf-8 -*-
"""cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IJdav4sMusHOD3q00lZgK9gk8NCQkN4
"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

from skimage.feature import graycomatrix, graycoprops, local_binary_pattern
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression

!pip install -q kaggle

from google.colab import files



import json

kaggle_creds = {
    "username": "saniagupta4",
    "key": "KGAT_3c9dbdef1a4b76e591656f756869cd6c"
}

with open("kaggle.json", "w") as f:
    json.dump(kaggle_creds, f)

print("kaggle.json created")



!ls

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets list

!kaggle datasets download -d ahmedaboenaba/tcga-stomach-histological-images

!ls

!unzip tcga-stomach-histological-images.zip -d stomach_data

import os

base_path = "stomach_data/stomach"
print(os.listdir(base_path))

import os
import cv2
import numpy as np
base_path = "stomach_data/stomach"

tumour_path = os.path.join(base_path, "tumour")
non_tumour_path = os.path.join(base_path, "non-tumour")
X = []   # images
y = []   # labels

IMG_SIZE = 128  # standard size

import os
print(os.getcwd())

!ls /content

!ls /content/stomach_data

!ls /content/stomach_data/stomach



tumour_path = "/content/stomach_data/stomach/tumour"
non_tumour_path = "/content/stomach_data/stomach/non-tumour"

import os
print("Tumour exists:", os.path.exists(tumour_path))
print("Non-tumour exists:", os.path.exists(non_tumour_path))

import os
import cv2
import numpy as np

X = []
y = []
IMG_SIZE = 128

# Tumour images → label 1
for img_name in os.listdir(tumour_path):
    img_path = os.path.join(tumour_path, img_name)
    img = cv2.imread(img_path)

    if img is None:
        continue

    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    X.append(img)
    y.append(1)

# Non-tumour images → label 0
for img_name in os.listdir(non_tumour_path):
    img_path = os.path.join(non_tumour_path, img_name)
    img = cv2.imread(img_path)

    if img is None:
        continue

    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    X.append(img)
    y.append(0)

X = np.array(X)
y = np.array(y)

print("Total images loaded:", X.shape[0])
print("Image shape:", X.shape[1:])
print("Tumour count:", np.sum(y == 1))
print("Non-tumour count:", np.sum(y == 0))

!pip install scikit-image

from skimage.feature import hog
import numpy as np

hog_features = []

for img in X:
    feature_vector = hog(
        img,
        orientations=9,
        pixels_per_cell=(8, 8),
        cells_per_block=(2, 2),
        block_norm='L2-Hys'
    )
    hog_features.append(feature_vector)

hog_features = np.array(hog_features)
print("HOG feature matrix shape:", hog_features.shape)

from sklearn.preprocessing import StandardScaler

# Initialize scaler
scaler = StandardScaler()

# Fit + transform HOG features
hog_features_scaled = scaler.fit_transform(hog_features)

print("Normalized feature matrix shape:", hog_features_scaled.shape)
print("Feature mean (approx):", np.mean(hog_features_scaled))
print("Feature std (approx):", np.std(hog_features_scaled))

from sklearn.model_selection import train_test_split



# Stratified split to preserve tumour / non-tumour ratio
X_train, X_test, y_train, y_test = train_test_split(
    hog_features_scaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training set shape:", X_train.shape, y_train.shape)
print("Testing set shape:", X_test.shape, y_test.shape)

print("Train tumour count:", np.sum(y_train == 1))
print("Train non-tumour count:", np.sum(y_train == 0))
print("Test tumour count:", np.sum(y_test == 1))
print("Test non-tumour count:", np.sum(y_test == 0))

# M1 : HOG +
# M1 (FAST BASELINE): SUBSET TRAINING
# ================================

SUBSET_SIZE = 6000  # safe on CPU

X_train_m1 = X_train[:SUBSET_SIZE]
y_train_m1 = y_train[:SUBSET_SIZE]

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

svm_m1 = LinearSVC(C=1.0, max_iter=3000)
svm_m1.fit(X_train_m1, y_train_m1)

y_pred_m1 = svm_m1.predict(X_test)
acc_m1 = accuracy_score(y_test, y_pred_m1) * 100

print(f"M1 (HOG + SVM, subset) Accuracy: {acc_m1:.2f}%")

#PCA
from sklearn.decomposition import IncrementalPCA

# Choose components explicitly (start small)
n_components = 500   # SAFE, FAST, STRONG

ipca = IncrementalPCA(n_components=n_components, batch_size=512)

print("Fitting Incremental PCA...")
X_train_pca = ipca.fit_transform(X_train)

print("Transforming test data...")
X_test_pca = ipca.transform(X_test)

print("Reduced feature count:", X_train_pca.shape[1])

from sklearn.svm import LinearSVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

#PCA+LINEAR SVM
# =====================================
# M2: PCA + Linear SVM
# =====================================

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Training M2: PCA + Linear SVM...")

svm_m2 = LinearSVC(C=1.0, max_iter=5000, random_state=42)
svm_m2.fit(X_train_pca, y_train)

y_pred_m2 = svm_m2.predict(X_test_pca)

acc_m2 = accuracy_score(y_test, y_pred_m2) * 100

print(f"\nM2 Accuracy: {acc_m2:.2f}%")
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_m2, target_names=["Non-Tumour", "Tumour"]))
print("Confusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_m2))

#DRAGONFLY+PCA+LINEAR SVM
# =====================================
# M3: Dragonfly + PCA + Linear SVM
# =====================================

import numpy as np
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# -------- Dragonfly Parameters --------
NUM_DRAGONFLIES = 8
MAX_ITER = 8
FEATURE_COUNT = X_train_pca.shape[1]

def fitness(mask, X, y):
    if np.sum(mask) == 0:
        return 0

    X_sel = X[:, mask == 1]

    X_tr, X_val, y_tr, y_val = train_test_split(
        X_sel, y, test_size=0.2, stratify=y, random_state=42
    )

    clf = LinearSVC(C=1.0, max_iter=3000)
    clf.fit(X_tr, y_tr)
    y_pred = clf.predict(X_val)

    return accuracy_score(y_val, y_pred)

# -------- Initialize Dragonflies --------
dragonflies = np.random.randint(0, 2, size=(NUM_DRAGONFLIES, FEATURE_COUNT))
fitness_scores = np.zeros(NUM_DRAGONFLIES)

best_mask = None
best_score = 0

print("Starting Dragonfly Optimization...")

for itr in range(MAX_ITER):
    print(f"Iteration {itr+1}/{MAX_ITER}")

    for i in range(NUM_DRAGONFLIES):
        score = fitness(dragonflies[i], X_train_pca, y_train)
        fitness_scores[i] = score

        if score > best_score:
            best_score = score
            best_mask = dragonflies[i].copy()

    for i in range(NUM_DRAGONFLIES):
        flip = np.random.rand(FEATURE_COUNT)
        dragonflies[i] = np.where(flip < 0.05, 1 - dragonflies[i], dragonflies[i])

print("Dragonfly completed.")
print("Selected features:", np.sum(best_mask))

# -------- Apply Selected Features --------
X_train_df_pca = X_train_pca[:, best_mask == 1]
X_test_df_pca = X_test_pca[:, best_mask == 1]

# -------- Train SVM --------
svm_m3 = LinearSVC(C=1.0, max_iter=5000)
svm_m3.fit(X_train_df_pca, y_train)

y_pred_m3 = svm_m3.predict(X_test_df_pca)

acc_m3 = accuracy_score(y_test, y_pred_m3) * 100

print(f"\nM3 Accuracy: {acc_m3:.2f}%")
print(classification_report(y_test, y_pred_m3, target_names=["Non-Tumour", "Tumour"]))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_m3))

# =====================================
# M4: Dragonfly + PCA + SNN
# =====================================

import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# -------- Spike Encoding --------
def rate_coding(X, time_steps=20):
    X_norm = (X - X.min()) / (X.max() - X.min() + 1e-9)
    spikes = np.random.rand(X.shape[0], X.shape[1], time_steps) < X_norm[:, :, None]
    return spikes.astype(int)

TIME_STEPS = 20

X_train_spikes = rate_coding(X_train_df_pca, TIME_STEPS)
X_test_spikes = rate_coding(X_test_df_pca, TIME_STEPS)

# -------- Simple SNN --------
class SimpleSNN:
    def __init__(self, n_features, threshold=10):
        self.weights = np.random.randn(n_features)
        self.threshold = threshold

    def train(self, X_spikes, y):
        for i in range(X_spikes.shape[0]):
            spike_sum = X_spikes[i].sum(axis=1)
            if y[i] == 1:
                self.weights += spike_sum
            else:
                self.weights -= spike_sum

    def predict(self, X_spikes):
        preds = []
        for i in range(X_spikes.shape[0]):
            spike_sum = X_spikes[i].sum(axis=1)
            membrane = np.dot(self.weights, spike_sum)
            preds.append(1 if membrane > self.threshold else 0)
        return np.array(preds)

# -------- Train & Evaluate --------
snn = SimpleSNN(n_features=X_train_df_pca.shape[1])
snn.train(X_train_spikes, y_train)

y_pred_snn = snn.predict(X_test_spikes)

acc_m4 = accuracy_score(y_test, y_pred_snn) * 100

print(f"\nM4 Accuracy: {acc_m4:.2f}%")
print(classification_report(y_test, y_pred_snn, target_names=["Non-Tumour", "Tumour"]))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_snn))

!ls /content/stomach_data

import os, random, shutil

base_dir = "/content/stomach_data/stomach"
subset_dir = "/content/stomach_data/stomach_subset"

# Clean old subset if partially created
if os.path.exists(subset_dir):
    shutil.rmtree(subset_dir)

os.makedirs(os.path.join(subset_dir, "tumour"), exist_ok=True)
os.makedirs(os.path.join(subset_dir, "non-tumour"), exist_ok=True)

def copy_subset(src, dst, max_images=3000):
    imgs = os.listdir(src)
    random.shuffle(imgs)
    for img in imgs[:max_images]:
        shutil.copy(os.path.join(src, img), os.path.join(dst, img))

copy_subset(os.path.join(base_dir, "tumour"),
            os.path.join(subset_dir, "tumour"),
            3000)

copy_subset(os.path.join(base_dir, "non-tumour"),
            os.path.join(subset_dir, "non-tumour"),
            3000)

print("Subset created successfully")
print("Tumour images:", len(os.listdir(subset_dir + "/tumour")))
print("Non-tumour images:", len(os.listdir(subset_dir + "/non-tumour")))

!ls /content/stomach_data/stomach_subset

# =====================================
# M5: CNN (MobileNetV2 – Transfer Learning)
# =====================================

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam

IMG_SIZE = 160
BATCH_SIZE = 16
EPOCHS = 5

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    "/content/stomach_data/stomach_subset",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='training'
)

val_generator = train_datagen.flow_from_directory(
    "/content/stomach_data/stomach_subset",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='validation'
)

base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)
base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation="relu")(x)
x = Dropout(0.5)(x)
output = Dense(1, activation="sigmoid")(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.fit(train_generator, validation_data=val_generator, epochs=EPOCHS)

val_loss, val_acc = model.evaluate(val_generator)
acc_m5 = val_acc * 100

print(f"\nM5 Accuracy (CNN): {acc_m5:.2f}%")

# FINAL COMPARISON
import pandas as pd

comparison = pd.DataFrame({
    "Model": ["M2", "M3", "M4", "M5"],
    "Method": [
        "PCA + Linear SVM",
        "Dragonfly + PCA + Linear SVM",
        "Dragonfly + PCA + SNN",
        "CNN (MobileNetV2)"
    ],
    "Accuracy (%)": [
        round(acc_m2, 2),
        round(acc_m3, 2),
        round(acc_m4, 2),
        round(acc_m5, 2)
    ]
})

print("\nFINAL MODEL COMPARISON\n")
print(comparison)

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=EPOCHS
)

val_loss, val_acc = model.evaluate(val_generator)
print("Validation Accuracy:", val_acc)

import matplotlib.pyplot as plt

# Accuracy plot
plt.figure()
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Verification and Validation Accuracy')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

models = ['M1\nHOG+SVM', 'M2\nPCA+SVM', 'M3\nDF+PCA+SVM', 'M4\nSNN', 'M5\nCNN']
accuracies = [60.17, 68.53, 68.17, 53.20, 84.33]

plt.figure(figsize=(7, 4))
bars = plt.bar(models, accuracies)

plt.xlabel('Models')
plt.ylabel('Accuracy (%)')
plt.title('Accuracy Comparison of Classification Models')
plt.ylim(0, 100)

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1,
             f'{yval:.2f}%', ha='center', fontsize=9)

plt.grid(axis='y')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# True labels and predicted labels
y_true = val_generator.classes
y_pred_prob = model.predict(val_generator)
y_pred = (y_pred_prob > 0.5).astype(int).ravel()

# Compute confusion matrix
cm = confusion_matrix(y_true, y_pred)

# Plot confusion matrix
plt.figure(figsize=(5, 4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['Non-Tumour', 'Tumour'],
    yticklabels=['Non-Tumour', 'Tumour']
)

plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix of CNN Model')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

# True labels
y_true = val_generator.classes

# Predicted probabilities
y_pred_prob = model.predict(val_generator).ravel()

# Compute ROC curve
fpr, tpr, thresholds = roc_curve(y_true, y_pred_prob)
roc_auc = auc(fpr, tpr)

# Plot ROC curve
plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, label=f'CNN (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], linestyle='--', label='Random Classifier')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for CNN Model')
plt.legend(loc='lower right')
plt.grid(True)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve, average_precision_score

# True labels
y_true = val_generator.classes

# Predicted probabilities
y_pred_prob = model.predict(val_generator).ravel()

# Compute Precision-Recall curve
precision, recall, thresholds = precision_recall_curve(y_true, y_pred_prob)
avg_precision = average_precision_score(y_true, y_pred_prob)

# Plot Precision-Recall curve
plt.figure(figsize=(6, 4))
plt.plot(recall, precision, label=f'CNN (AP = {avg_precision:.4f})')

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision–Recall Curve for CNN Model')
plt.legend(loc='lower left')
plt.grid(True)

plt.tight_layout()
plt.show()

